version: "3.7"
# apenas banco de dados
services:
  geostore-postgres:
    image: kartoza/postgis:12.0
    container_name: geostore_postgis
    volumes:
      - geostore_pg:/var/lib/postgresql
    environment:
      - "POSTGRES_DB=geostore"
      - "POSTGRES_USER=willian"
      - "POSTGRES_PASSWORD=123456"
      - "ALLOW_IP_RANGE=0.0.0.0/0"
    ports:
      - "5432:5432" #local only
    networks:
      - default

  geostore-mapserver:
    image: camptocamp/mapserver:7.4
    container_name: geostore-mapserver
    volumes:
      - ./mapfiles/:/etc/mapserver/
    environment:
      - "BUSY_TIMEOUT=20"
    ports:
      - "8080:80"
    networks:
      - default

  # geostore-redis:
  #   image: bitnami/redis:latest
  #   environment:
  #     - ALLOW_EMPTY_PASSWORD=yes
  #     - REDIS_PASSWORD=123456
  #   ports:
  #     - '6379:6379'
  #   volumes:
  #     - geostore_redis:/bitnami/redis/data
  #   networks:
  #     - default

volumes:
  geostore_pg:
  geostore_redis:

networks:
  default:
